#
python3.5 ldc_evoml_regression_v0p3.py -r  01 > ./output/ldc_evoml_regression_v0p3__surucucu_01.out &
python3.5 ldc_evoml_regression_v0p3.py -r  02 > ./output/ldc_evoml_regression_v0p3__surucucu_02.out &
python3.5 ldc_evoml_regression_v0p3.py -r  03 > ./output/ldc_evoml_regression_v0p3__surucucu_03.out &
python3.5 ldc_evoml_regression_v0p3.py -r  04 > ./output/ldc_evoml_regression_v0p3__surucucu_04.out &
python3.5 ldc_evoml_regression_v0p3.py -r  05 > ./output/ldc_evoml_regression_v0p3__surucucu_05.out &
python3.5 ldc_evoml_regression_v0p3.py -r  06 > ./output/ldc_evoml_regression_v0p3__surucucu_06.out &
python3.5 ldc_evoml_regression_v0p3.py -r  07 > ./output/ldc_evoml_regression_v0p3__surucucu_07.out &
python3.5 ldc_evoml_regression_v0p3.py -r  08 > ./output/ldc_evoml_regression_v0p3__surucucu_08.out &
python3.5 ldc_evoml_regression_v0p3.py -r  09 > ./output/ldc_evoml_regression_v0p3__surucucu_09.out &
python3.5 ldc_evoml_regression_v0p3.py -r  10 > ./output/ldc_evoml_regression_v0p3__surucucu_10.out &
python3.5 ldc_evoml_regression_v0p3.py -r  11 > ./output/ldc_evoml_regression_v0p3__surucucu_11.out &
python3.5 ldc_evoml_regression_v0p3.py -r  12 > ./output/ldc_evoml_regression_v0p3__surucucu_12.out &
python3.5 ldc_evoml_regression_v0p3.py -r  13 > ./output/ldc_evoml_regression_v0p3__surucucu_13.out &
python3.5 ldc_evoml_regression_v0p3.py -r  14 > ./output/ldc_evoml_regression_v0p3__surucucu_14.out &
python3.5 ldc_evoml_regression_v0p3.py -r  15 > ./output/ldc_evoml_regression_v0p3__surucucu_15.out &
python3.5 ldc_evoml_regression_v0p3.py -r  16 > ./output/ldc_evoml_regression_v0p3__surucucu_16.out &
python3.5 ldc_evoml_regression_v0p3.py -r  17 > ./output/ldc_evoml_regression_v0p3__surucucu_17.out &
python3.5 ldc_evoml_regression_v0p3.py -r  18 > ./output/ldc_evoml_regression_v0p3__surucucu_18.out &
python3.5 ldc_evoml_regression_v0p3.py -r  19 > ./output/ldc_evoml_regression_v0p3__surucucu_19.out &
python3.5 ldc_evoml_regression_v0p3.py -r  20 > ./output/ldc_evoml_regression_v0p3__surucucu_20.out &
python3.5 ldc_evoml_regression_v0p3.py -r  21 > ./output/ldc_evoml_regression_v0p3__surucucu_21.out &
python3.5 ldc_evoml_regression_v0p3.py -r  22 > ./output/ldc_evoml_regression_v0p3__surucucu_22.out &
python3.5 ldc_evoml_regression_v0p3.py -r  23 > ./output/ldc_evoml_regression_v0p3__surucucu_23.out &
python3.5 ldc_evoml_regression_v0p3.py -r  24 > ./output/ldc_evoml_regression_v0p3__surucucu_24.out &
python3.5 ldc_evoml_regression_v0p3.py -r  25 > ./output/ldc_evoml_regression_v0p3__surucucu_25.out &
python3.5 ldc_evoml_regression_v0p3.py -r  26 > ./output/ldc_evoml_regression_v0p3__surucucu_26.out &
python3.5 ldc_evoml_regression_v0p3.py -r  27 > ./output/ldc_evoml_regression_v0p3__surucucu_27.out &
python3.5 ldc_evoml_regression_v0p3.py -r  28 > ./output/ldc_evoml_regression_v0p3__surucucu_28.out &
python3.5 ldc_evoml_regression_v0p3.py -r  29 > ./output/ldc_evoml_regression_v0p3__surucucu_29.out &
python3.5 ldc_evoml_regression_v0p3.py -r  30 > ./output/ldc_evoml_regression_v0p3__surucucu_30.out &
